name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              since: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(), // Last 24 hours
              per_page: 100
            });

            const changes = commits
              .filter(commit => !commit.commit.message.includes('chore: bump version'))
              .map(commit => `- ${commit.commit.message.split('\n')[0]}`)
              .join('\n');

            return changes || '- No significant changes';

      - name: Update release notes
        if: steps.changelog.outputs.result
        uses: actions/github-script@v7
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });

            if (releases.length > 0) {
              const latestRelease = releases[0];
              const changelog = '${{ steps.changelog.outputs.result }}';
              
              await github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: latestRelease.id,
                body: `${latestRelease.body}\n\n## Recent Changes\n${changelog}`
              });
            }
