name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Run linting
        run: pnpm lint

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Get current versions and generate new versions
        id: versions
        run: |
          # Get current versions from package.json files
          CORE_VERSION=$(node -p "require('./packages/core/package.json').version")
          SHARED_VERSION=$(node -p "require('./packages/shared/package.json').version")

          echo "core_version=$CORE_VERSION" >> $GITHUB_OUTPUT
          echo "shared_version=$SHARED_VERSION" >> $GITHUB_OUTPUT

          # Generate new versions by incrementing patch version
          CORE_MAJOR=$(echo $CORE_VERSION | cut -d. -f1)
          CORE_MINOR=$(echo $CORE_VERSION | cut -d. -f2)
          CORE_PATCH=$(echo $CORE_VERSION | cut -d. -f3)
          NEW_CORE_PATCH=$((CORE_PATCH + 1))
          NEW_CORE_VERSION="${CORE_MAJOR}.${CORE_MINOR}.${NEW_CORE_PATCH}"

          SHARED_MAJOR=$(echo $SHARED_VERSION | cut -d. -f1)
          SHARED_MINOR=$(echo $SHARED_VERSION | cut -d. -f2)
          SHARED_PATCH=$(echo $SHARED_VERSION | cut -d. -f3)
          NEW_SHARED_PATCH=$((SHARED_PATCH + 1))
          NEW_SHARED_VERSION="${SHARED_MAJOR}.${SHARED_MINOR}.${NEW_SHARED_PATCH}"

          echo "new_core_version=$NEW_CORE_VERSION" >> $GITHUB_OUTPUT
          echo "new_shared_version=$NEW_SHARED_VERSION" >> $GITHUB_OUTPUT

          echo "Current versions - Core: $CORE_VERSION, Shared: $SHARED_VERSION"
          echo "New versions - Core: $NEW_CORE_VERSION, Shared: $NEW_SHARED_VERSION"

      - name: Update package versions
        run: |
          # Update core package version
          cd packages/core
          echo "Updating core package from ${{ steps.versions.outputs.core_version }} to ${{ steps.versions.outputs.new_core_version }}"
          pnpm version ${{ steps.versions.outputs.new_core_version }} --no-git-tag-version

          # Update shared package version
          cd ../shared
          echo "Updating shared package from ${{ steps.versions.outputs.shared_version }} to ${{ steps.versions.outputs.new_shared_version }}"
          pnpm version ${{ steps.versions.outputs.new_shared_version }} --no-git-tag-version

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.versions.outputs.new_core_version }}
          name: Release v${{ steps.versions.outputs.new_core_version }}
          body: |
            ## Changes in this release

            - Updated @nearux/flow to v${{ steps.versions.outputs.new_core_version }}
            - Updated @nearux/shared to v${{ steps.versions.outputs.new_shared_version }}

            ### Packages
            - **@nearux/flow**: React components and utilities
            - **@nearux/shared**: Shared utilities and types
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          cd packages/core && pnpm publish --access public --no-git-checks
          cd ../shared && pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit version changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: bump version to v${{ steps.versions.outputs.new_core_version }}"
          git push
